"""Populate movie data from CSV

Revision ID: 7965efeb8446
Revises: 6f0f19c6d605
Create Date: 2023-08-08 00:16:10.904081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import create_engine, Table, MetaData
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '7965efeb8446'
down_revision: Union[str, None] = '6f0f19c6d605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        LOAD DATA INFILE '/var/lib/mysql-files/data/movies.csv'
        INTO TABLE movie
        FIELDS TERMINATED BY ',' 
        ENCLOSED BY '"'
        LINES TERMINATED BY '\\n'
        IGNORE 1 ROWS;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
