<<<<<<< HEAD
version: '3.8'

services:
  db:
    image: mysql:8.0
    platform: ${PLATFORM} #linux/arm64 linux/amd64
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    env_file:
      - .env

  web:
      build: ./server
      volumes:
        - ./server:/app
      ports:
        - 8000:8000
      depends_on:
        - db
      env_file:
        - .env

volumes:
=======
version: '3.8'

services:
  db:
    image: mysql:8.0
    platform: ${PLATFORM} #linux/arm64 linux/amd64
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    env_file:
      - .env

  web:
      build: ./server
      volumes:
        - ./server:/app
      ports:
        - 8000:8000
      depends_on:
        - db
      env_file:
        - .env

volumes:
>>>>>>> 855585e (fixed)
  mysql-data: