version: '3.1'

services:
  db:
    image: mysql:latest  
    platform: linux/arm64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: mydb
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

  web:
      build: ./server
      volumes:
        - ./server:/app
      ports:
        - 8000:8000
      depends_on:
        - db

volumes:
  mysql-data: