version: '3.8'

services:
  db:
    image: mysql:8.0
    platform: ${PLATFORM} #linux/arm64 linux/amd64
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d:ro
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    env_file:
      - .env
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-time-zone=+03:00']

  web:
      build: ./server
      volumes:
        - ./server:/app
      ports:
        - 8000:8000
      environment:
        GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
        GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
        SECRET_KEY: ${SECRET_KEY}
      depends_on:
        - db
      env_file:
        - .env
  
  client:
    build:
      context: ./client
    environment:
      SERVER_URL: ${SERVER_URL}
    depends_on:
        - web
   


volumes:
  mysql-data: