from pydantic import BaseModel, Field
from typing import Optional


class MovieBase(BaseModel):
    Name: str = Field(
        ..., description="The name of the movie.", example="Inception"
        )
    Year: int = Field(
        ..., description="The release year of the movie.", example=2010
        )
    Runtime: int = Field(
        ..., description="The runtime of the movie in minutes.", example=148
        )
    Rating: float = Field(
        ..., description="The rating of the movie out of 10.", example=8.8
        )
    Votes: int = Field(
        ..., description="The number of votes the movie received.", example=2000000
        )
    Revenue: Optional[float] = Field(
        None, description="The revenue generated by the movie in millions.", example=292.58
        )


class MovieCreate(MovieBase):
    pass


class Movie(MovieBase):
    MovieID: Optional[int] = Field(
        default=None, primary_key=True, description="The unique ID of the movie.", example=1
        )
    
    class Config:
        from_attributes = True
