name: Docker Compose Build and Run

on:
  workflow_dispatch:
  push:
    branches:
      - dev  # or your default branch name

jobs:
  docker-compose:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: 'Create env file'
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env

    - name: Build and run with Docker Compose
      run: |
        docker-compose up --build
        
    - name: Stop Containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down


